name: untitled63
description: A new Flutter project.

publish_to: none


version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2


  #State manager :D
  provider: ^6.0.4


  http: ^0.13.5
  palette_generator: ^0.3.3+2

  #Utilites
  cached_network_image: ^3.2.3
  shared_preferences: ^2.0.15
  connectivity_plus: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

